interface State {
  value: string;
  viewValue: string;
}

export const State: State[] = [
    {value: 'Alabama', viewValue: 'AL'},
    {value: 'Alaska', viewValue: 'AK'},
    {value: 'Arizona', viewValue: 'AZ'},
    {value: 'Arkansas', viewValue: 'AR'},
    {value: 'California', viewValue: 'CA'},
    {value: 'Colorado', viewValue: 'CO'},
    {value: 'Connecticut', viewValue: 'CT'},
    {value: 'Delaware', viewValue: 'DE'},
    {value: 'Florida', viewValue: 'FL'},
    {value: 'Georgia', viewValue: 'GA'},
    {value: 'Hawaii', viewValue: 'HI'},
    {value: 'Idaho', viewValue: 'ID'},
    {value: 'Illinois', viewValue: 'IL'},
    {value: 'Indiana', viewValue: 'IN'},
    {value: 'Iowa', viewValue: 'IA'},
    {value: 'Kansas', viewValue: 'KS'},
    {value: 'Kentucky', viewValue: 'KY'},
    {value: 'Louisiana', viewValue: 'LA'},
    {value: 'Maine', viewValue: 'ME'},
    {value: 'Maryland', viewValue: 'MD'},
    {value: 'Massachusetts', viewValue: 'MA'},
    {value: 'Michigan', viewValue: 'MI'},
    {value: 'Minnesota', viewValue: 'MN'},
    {value: 'Mississippi', viewValue: 'MS'},
    {value: 'Missouri', viewValue: 'MO'},
    {value: 'Montana', viewValue: 'MT'},
    {value: 'Nebraska', viewValue: 'NE'},
    {value: 'Nevada', viewValue: 'NV'},
    {value: 'New Hampshire', viewValue: 'NH'},
    {value: 'New Jersey', viewValue: 'NJ'},
    {value: 'New Mexico', viewValue: 'NM'},
    {value: 'New York', viewValue: 'NY'},
    {value: 'North Carolina', viewValue: 'NC'},
    {value: 'North Dakota', viewValue: 'ND'},
    {value: 'Ohio', viewValue: 'OH'},
    {value: 'Oklahoma', viewValue: 'OK'},
    {value: 'Oregon', viewValue: 'OR'},
    {value: 'Pennsylvania', viewValue: 'PA'},
    {value: 'Rhode Island', viewValue: 'RI'},
    {value: 'South Carolina', viewValue: 'SC'},
    {value: 'South Dakota', viewValue: 'SD'},
    {value: 'Tennessee', viewValue: 'TN'},
    {value: 'Texas', viewValue: 'TX'},
    {value: 'Utah', viewValue: 'UT'},
    {value: 'Vermont', viewValue: 'VT'},
    {value: 'Virginia', viewValue: 'VA'},
    {value: 'Washington', viewValue: 'WA'},
    {value: 'West Virginia', viewValue: 'WV'},
    {value: 'Wisconsin', viewValue: 'WI'},
    {value: 'Wyoming', viewValue: 'WY'}
];

