version: '3'


services:
  great-blue-fishing-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: gallowaystorm/great-blue-fishing-frontend
    container_name: great-blue-fishing-frontend
    ports:
      - 80:80
